site_name: 何子豪的个人网站
site_url: https://he-zihao.github.io
site_author: He-Zihao
site_description: 何子豪的个人网站

# [Navigtion]
nav:
  - Home:
    - index.md
  - speaking:
    - speaking/index.md
    - Part 1:
      - 1.T-shirts:     speaking/P1/1.T-shirts.md
      - 2.Stay up late: speaking/P1/2.Stay up late.md
      - 3.Jewelry:      speaking/P1/3.Jewelry.md
      - 4.Music:        speaking/P1/4.Music.md
      - 5.Art:          speaking/P1/5.Art.md
      - 6.Library:      speaking/P1/6.Library.md
      - 7.Schools:      speaking/P1/7.Schools.md
      - 8.Weekends:     speaking/P1/8.Weekends.md
      - 9.Happiness:    speaking/P1/9.Happiness.md
      - 10.Outer space and stars: speaking/P1/10.Outer space and stars.md
      - 11.Small businesses: speaking/P1/11.Small businesses.md
      - 12.Keys:        speaking/P1/12.Keys.md
      - 13.Chocolate:   speaking/P1/13.Chocolate.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
